# Generated by Django 4.1.1 on 2022-10-14 15:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('thumbnail', models.ImageField(default='default.png', null=True, upload_to='pics')),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_content',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='creater',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapp.info'),
        ),
    ]
