# Generated by Django 4.1.1 on 2022-10-14 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_info_alter_todo_todo_content_todo_creater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='creater',
        ),
        migrations.AddField(
            model_name='todo',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
