# Generated by Django 4.1.1 on 2022-10-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_info_remove_todo_date_time_remove_todo_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapp.info'),
        ),
    ]
