# Generated by Django 4.1.1 on 2022-10-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_alter_todo_creater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', null=True, upload_to='pics'),
        ),
    ]
